import { S, $, html, text, esc, fullName, person, titleCaseName, uid, status, userId, userName, canDelete, canEdit, visiblePeople } from './state.js';
import { publicUrl, bucket, loadAll, addOptional } from './api.js';
import { avatarHtml, cropStyle, faceForPerson, personOptions, photoTitle } from './render.js';
import { renderPeople } from './people.js';

export async function renderPhotoPage(){await renderCurrentPhoto(); await renderPhotos(); await renderPhotoPeople(); renderFaceEditor(); renderPhotoStats(); renderComments(); fillRelationshipSelects()}
export async function renderPhotos(){
  const box=$('photoList'); if(!box)return; if(!S.photos.length){box.innerHTML='<p class="small">No photos yet.</p>';return}
  let out=''; for(const ph of S.photos){const url=await publicUrl(ph); const fc=S.faces.filter(f=>f.photo_id===ph.id).length; const nc=S.faces.filter(f=>f.photo_id===ph.id&&f.person_id).length; const d=ph.date_taken||ph.photo_date||ph.taken_at||ph.created_at?.slice(0,10)||''; out+=`<button class="photo-list-item ${S.currentPhoto?.id===ph.id?'active':''}" data-photo-id="${ph.id}"><img src="${url}"><span><b>${esc(photoTitle(ph))}</b><small>${esc(d)} · ${fc} face${fc===1?'':'s'}${nc?` · ${nc} named`:''}</small></span></button>`}
  box.innerHTML=out;
}
export async function renderPhotoPeople(){const box=$('photoPeopleNav'); if(!box)return; let out=''; for(const p of visiblePeople().slice(0,30)){const f=faceForPerson(p.id); out+=`<div class="photo-person-link" data-person-id="${p.id}"><div class="tiny-avatar" style="${f?await cropStyle(f,34):''}">${f?'':esc((fullName(p)[0]||'?').toUpperCase())}</div><div><b>${esc(fullName(p))}</b><br><span class="small">${esc(p.birth_date||'')}</span></div><span class="blue-dot"></span></div>`} box.innerHTML=out||'<p class="small">No people yet.</p>'}
export async function renderCurrentPhoto(){
  const img=$('mainPhoto'), empty=$('emptyPhoto'), c=$('photoCanvas'); if(!c)return;
  c.querySelectorAll('.face').forEach(x=>x.remove());
  if(img) img.src=S.currentPhoto?await publicUrl(S.currentPhoto):'';
  if(empty) empty.style.display=S.currentPhoto?'none':'grid';
  if(!S.currentPhoto)return;
  S.faces.filter(f=>f.photo_id===S.currentPhoto.id).forEach(f=>c.appendChild(faceEl(f)));
  c.classList.toggle('hide-boxes',!S.showBoxes); c.classList.toggle('hide-names',!S.showNames);
  $('photoDate') && ($('photoDate').value=S.currentPhoto.date_taken||S.currentPhoto.photo_date||S.currentPhoto.taken_at||'');
  $('photoPlace') && ($('photoPlace').value=S.currentPhoto.location||S.currentPhoto.place||'');
}
function faceEl(f){const d=document.createElement('div'); d.className='face'+(f.person_id?' named':'')+(f.id===S.selectedFaceId?' selected':''); d.style.left=(+f.x||0)+'px'; d.style.top=(+f.y||0)+'px'; d.style.width=(+f.w||70)+'px'; d.style.height=(+f.h||90)+'px'; d.innerHTML=`<span>${esc(f.label||'')}</span><div class="handle"></div>`; d.addEventListener('pointerdown',e=>startDrag(e,f.id)); d.querySelector('.handle').addEventListener('pointerdown',e=>startResize(e,f.id)); d.addEventListener('click',e=>{e.stopPropagation();S.selectedFaceId=f.id;renderPhotoPage()}); return d}
export function renderFaceEditor(){
  const w=$('faceEditor'); if(!w)return; const f=S.faces.find(x=>x.id===S.selectedFaceId);
  if(!f){w.innerHTML='<p>Select or add a face box.</p><button class="full" id="suggestFaceInline">Suggest a face/name</button>';return}
  const p=f.person_id?person(f.person_id):null;
  if(!canEdit()){w.innerHTML=`<p><strong>${esc(p?fullName(p):(f.label||'Unnamed'))}</strong></p><textarea id="faceSuggestionText" placeholder="Suggest a correction…"></textarea><button class="primary full" id="sendFaceSuggestion">Send suggestion</button>`;return}
  w.innerHTML=`<div class="selected-face-summary"><p class="small">Current</p><strong>${esc(p?fullName(p):(f.label||'Unnamed face'))}</strong></div><div class="form-grid compact-form"><label>Use existing person<select id="existingPersonSelect">${personOptions(f.person_id||'')}</select></label><button class="primary full" id="attachExistingBtn">Use selected person</button><label>Create new person<input id="faceName" value="${esc(p?fullName(p):(f.label||''))}" placeholder="Type a new full name"></label><button class="full" id="saveTypedFaceBtn">Create / save typed name</button><button class="full" id="suggestCorrectionBtn">Suggest correction instead</button></div>`;
}
export function renderPhotoStats(){text('faceCount',S.currentPhoto?S.faces.filter(f=>f.photo_id===S.currentPhoto.id).length:0); text('namedCount',S.currentPhoto?S.faces.filter(f=>f.photo_id===S.currentPhoto.id&&f.person_id).length:0); text('toggleBoxesBtn',S.showBoxes?'Hide boxes':'Show boxes'); text('toggleNamesBtn',S.showNames?'Hide names':'Show names')}
export function renderComments(){const box=$('photoComments'); if(!box)return; const rows=S.comments.filter(c=>c.photo_id===S.currentPhoto?.id).slice(0,20); box.innerHTML=rows.length?rows.map(c=>`<div class="comment"><b>${esc(c.author_name||c.created_by||'Family member')}</b><br>${esc(c.body||c.comment||'')}</div>`).join(''):'No comments yet.'}
function fillRelationshipSelects(){const opts=visiblePeople().map(p=>`<option value="${p.id}">${esc(fullName(p))}</option>`).join(''); html('relA',opts); html('relB',opts)}
export async function selectPhoto(id){const ph=S.photos.find(p=>p.id===id); if(!ph)return; S.currentPhoto=ph; S.selectedFaceId=null; await renderPhotoPage(); status('Photo loaded')}
export async function uploadPhoto(ev){const file=ev.target.files?.[0]; if(!file)return; status('Uploading photo…'); const id=uid(), ext=(file.name.split('.').pop()||'jpg').toLowerCase(), path=`photos/${id}/original.${ext}`; const up=await S.sb.storage.from(bucket()).upload(path,file,{upsert:false}); if(up.error)return alert(up.error.message); const ins=await S.sb.from('photos').insert({id,title:file.name,storage_path:path,original_filename:file.name,mime_type:file.type,uploaded_by:userId()}).select().single(); if(ins.error)return alert(ins.error.message); S.photos.unshift(ins.data); S.currentPhoto=ins.data; await renderPhotoPage(); status('Photo saved'); setTimeout(()=>detectFaces(true),350)}
export async function latestPhoto(){if(S.photos[0])await selectPhoto(S.photos[0].id)}
export async function prevPhoto(){const i=S.photos.findIndex(p=>p.id===S.currentPhoto?.id); if(i>0)await selectPhoto(S.photos[i-1].id)}
export async function nextPhoto(){const i=S.photos.findIndex(p=>p.id===S.currentPhoto?.id); if(i>=0&&i<S.photos.length-1)await selectPhoto(S.photos[i+1].id)}
export async function addFaceBox(){if(!S.currentPhoto)return alert('Upload a photo first.'); const ins=await S.sb.from('faces').insert({photo_id:S.currentPhoto.id,x:160,y:120,w:90,h:110,label:null,status:'manual',created_by:userId()}).select().single(); if(ins.error)return alert(ins.error.message); S.faces.push(ins.data); S.selectedFaceId=ins.data.id; await renderPhotoPage(); status('Face saved')}
export async function attachExisting(){const f=S.faces.find(x=>x.id===S.selectedFaceId), pid=$('existingPersonSelect')?.value; if(!f||!pid)return alert('Choose an existing person first.'); const p=person(pid); const upd=await S.sb.from('faces').update({person_id:pid,label:fullName(p),status:'confirmed'}).eq('id',f.id).select().single(); if(upd.error)return alert(upd.error.message); Object.assign(f,upd.data); await renderPhotoPage(); await renderPeople(); status('Face linked')}
export async function saveFaceName(){const f=S.faces.find(x=>x.id===S.selectedFaceId), name=titleCaseName($('faceName')?.value||''); if(!f||!name)return; let p=S.people.find(x=>fullName(x).toLowerCase()===name.toLowerCase()); if(!p){const parts=name.split(' '); const ins=await S.sb.from('people').insert({display_name:name,given_names:parts[0]||name,family_name:parts.slice(1).join(' ')||null,created_by:userId()}).select().single(); if(ins.error)return alert(ins.error.message); p=ins.data; S.people.push(p)} const upd=await S.sb.from('faces').update({person_id:p.id,label:fullName(p),status:'confirmed'}).eq('id',f.id).select().single(); if(upd.error)return alert(upd.error.message); Object.assign(f,upd.data); await renderPhotoPage(); await renderPeople(); status('Face saved')}
export async function deleteFace(){if(!canDelete())return alert('Only owner can delete.'); if(!S.selectedFaceId)return; const del=await S.sb.from('faces').delete().eq('id',S.selectedFaceId); if(del.error)return alert(del.error.message); S.faces=S.faces.filter(f=>f.id!==S.selectedFaceId); S.selectedFaceId=null; await renderPhotoPage()}
export async function savePhotoMeta(){if(!S.currentPhoto)return; const patch={}; const d=$('photoDate')?.value||null, loc=$('photoPlace')?.value||null; ['date_taken','photo_date','taken_at'].forEach(k=>{if(k in S.currentPhoto)patch[k]=d}); ['location','place'].forEach(k=>{if(k in S.currentPhoto)patch[k]=loc}); if(!Object.keys(patch).length)return alert('No editable photo date/place columns found.'); const r=await S.sb.from('photos').update(patch).eq('id',S.currentPhoto.id).select().single(); if(r.error)return alert(r.error.message); Object.assign(S.currentPhoto,r.data); await renderPhotos(); status('Photo details saved')}
export async function postComment(){const body=$('commentText')?.value.trim(); if(!body)return; const row=await addOptional('comments',{photo_id:S.currentPhoto?.id,body,author_id:userId(),author_name:userName(),status:'open'}); S.comments.unshift(row); $('commentText').value=''; renderComments()}
export async function suggestFace(){const body=prompt('Who or what should be corrected/added?'); if(!body)return; const row=await addOptional('suggestions',{type:'photo_face_suggestion',photo_id:S.currentPhoto?.id,face_id:S.selectedFaceId,body,suggested_value:body,author_id:userId(),author_name:userName(),status:'open'}); S.suggestions.unshift(row); alert('Suggestion added for review.')}
let drag=null;
function startDrag(ev,id){if(ev.target.classList.contains('handle')||!S.editMode)return; ev.preventDefault(); S.selectedFaceId=id; const f=S.faces.find(x=>x.id===id); drag={mode:'move',id,sx:ev.clientX,sy:ev.clientY,x:+f.x||0,y:+f.y||0}; window.addEventListener('pointermove',move); window.addEventListener('pointerup',end); renderFaceEditor()}
function startResize(ev,id){if(!S.editMode)return; ev.preventDefault(); ev.stopPropagation(); S.selectedFaceId=id; const f=S.faces.find(x=>x.id===id); drag={mode:'resize',id,sx:ev.clientX,sy:ev.clientY,w:+f.w||70,h:+f.h||90}; window.addEventListener('pointermove',move); window.addEventListener('pointerup',end)}
function move(ev){if(!drag)return; const f=S.faces.find(x=>x.id===drag.id); if(!f)return; if(drag.mode==='move'){f.x=Math.max(0,drag.x+ev.clientX-drag.sx); f.y=Math.max(0,drag.y+ev.clientY-drag.sy)} else {f.w=Math.max(24,drag.w+ev.clientX-drag.sx); f.h=Math.max(24,drag.h+ev.clientY-drag.sy)} const box=document.querySelector('.face.selected'); if(box){box.style.left=f.x+'px';box.style.top=f.y+'px';box.style.width=f.w+'px';box.style.height=f.h+'px'}}
async function end(){if(drag){const f=S.faces.find(x=>x.id===drag.id); if(f)await S.sb.from('faces').update({x:f.x,y:f.y,w:f.w,h:f.h}).eq('id',f.id)} drag=null; window.removeEventListener('pointermove',move); window.removeEventListener('pointerup',end)}
function waitForImage(img){return new Promise((res,rej)=>{if(!img)return rej(new Error('Photo missing')); if(img.complete&&img.naturalWidth)return res(img); img.onload=()=>res(img); img.onerror=()=>rej(new Error('Photo failed to load'))})}
function iou(a,b){const ax=a.x+a.w,ay=a.y+a.h,bx=b.x+b.w,by=b.y+b.h,ix=Math.max(0,Math.min(ax,bx)-Math.max(a.x,b.x)),iy=Math.max(0,Math.min(ay,by)-Math.max(a.y,b.y)),inter=ix*iy; return inter/(a.w*a.h+b.w*b.h-inter||1)}
async function detector(){if(S.humanPromise)return S.humanPromise; S.humanPromise=(async()=>{if(!window.Human)throw new Error('Face detector library did not load.'); S.human=new Human.Human({modelBasePath:'https://cdn.jsdelivr.net/npm/@vladmandic/human/models/',backend:'webgl',face:{enabled:true,detector:{enabled:true,rotation:true,maxDetected:100},mesh:{enabled:false},iris:{enabled:false},description:{enabled:false},emotion:{enabled:false}},body:{enabled:false},hand:{enabled:false},object:{enabled:false},gesture:{enabled:false}}); status('Loading face detector…'); await S.human.load(); await S.human.warmup(); return S.human})(); return S.humanPromise}
export async function detectFaces(auto=false){try{if(!S.currentPhoto)return; const img=$('mainPhoto'); await waitForImage(img); const det=await detector(); status('Detecting faces…'); const r=await det.detect(img); const scale=(img.clientWidth||img.naturalWidth)/(img.naturalWidth||img.clientWidth||1); const found=(r.face||[]).map(fc=>{const b=fc.box||fc.boxRaw||[];return{x:Math.round((b[0]||0)*scale),y:Math.round((b[1]||0)*scale),w:Math.round((b[2]||0)*scale),h:Math.round((b[3]||0)*scale)}}).filter(x=>x.w>=24&&x.h>=24); const exist=S.faces.filter(f=>f.photo_id===S.currentPhoto.id).map(f=>({x:+f.x||0,y:+f.y||0,w:+f.w||0,h:+f.h||0})); const fresh=found.filter(x=>!exist.some(e=>iou(e,x)>.35)); if(!fresh.length){status(found.length?'Detected; all already boxed':'No faces detected'); if(!auto&&!found.length)alert('No faces detected. Use Add face box.'); return} const rows=fresh.map(x=>({...x,photo_id:S.currentPhoto.id,label:null,status:'detected',created_by:userId()})); const ins=await S.sb.from('faces').insert(rows).select(); if(ins.error)return alert(ins.error.message); S.faces.push(...ins.data); await renderPhotoPage(); status(`Detected ${fresh.length} new face${fresh.length===1?'':'s'}`)}catch(e){console.error(e); status('Face detection unavailable'); if(!auto)alert(e.message)}}
export function bindPhotos(){document.body.addEventListener('click',e=>{const p=e.target.closest('[data-photo-id]'); if(p)selectPhoto(p.dataset.photoId)}); $('photoInput')?.addEventListener('change',uploadPhoto); $('latestPhotoBtn')?.addEventListener('click',latestPhoto); $('prevPhotoBtn')?.addEventListener('click',prevPhoto); $('nextPhotoBtn')?.addEventListener('click',nextPhoto); $('addFaceBtn')?.addEventListener('click',addFaceBox); $('detectFacesBtn')?.addEventListener('click',()=>detectFaces(false)); $('deleteFaceBtn')?.addEventListener('click',deleteFace); $('toggleBoxesBtn')?.addEventListener('click',()=>{S.showBoxes=!S.showBoxes;renderPhotoPage()}); $('toggleNamesBtn')?.addEventListener('click',()=>{S.showNames=!S.showNames;renderPhotoPage()}); $('suggestFaceBtn')?.addEventListener('click',suggestFace); $('savePhotoMetaBtn')?.addEventListener('click',savePhotoMeta); $('postCommentBtn')?.addEventListener('click',postComment); document.body.addEventListener('click',e=>{if(e.target.id==='attachExistingBtn')attachExisting(); if(e.target.id==='saveTypedFaceBtn')saveFaceName(); if(e.target.id==='suggestCorrectionBtn'||e.target.id==='suggestFaceInline')suggestFace()}); $('mainPhoto')?.addEventListener('click',()=>{if(!S.editMode){S.selectedFaceId=null;renderFaceEditor()}})}
