import { S, $, html, esc, fullName, person, canDelete } from './state.js';
import { renderPage } from './render.js';
export function relationshipSentence(r){const a=person(r.from_person_id),b=person(r.to_person_id); if(!a||!b)return'Missing person'; if(r.relationship_type==='parent')return`${fullName(a)} is ${r.label||'parent'} of ${fullName(b)}`; if(r.relationship_type==='partner')return`${fullName(a)} is partner of ${fullName(b)}`; if(r.relationship_type==='sibling')return`${fullName(a)} is sibling of ${fullName(b)}`; return`${fullName(a)} → ${fullName(b)}`}
export function renderRelationshipList(){html('relationshipList',S.relationships.map(r=>`<div class="rel-row"><div><strong>${esc(relationshipSentence(r))}</strong></div><button class="danger" data-delete-rel="${r.id}">Delete</button></div>`).join('')||'<p>No relationships yet.</p>')}
function candidate(){let a=$('relA')?.value,b=$('relB')?.value,type=S.currentRel,from=a,to=b,label=type; if(['mother','father','parent'].includes(type)){type='parent';label=S.currentRel}else if(type==='child'){type='parent';from=b;to=a;label='parent'} return{from,to,type,label}}
function parentsOf(id){return S.relationships.filter(r=>r.relationship_type==='parent'&&r.to_person_id===id).map(r=>r.from_person_id)}
function ancestor(a,d,seen=new Set()){if(seen.has(d))return false; seen.add(d); const ps=parentsOf(d); return ps.includes(a)||ps.some(p=>ancestor(a,p,seen))}
export function validateRelationship(from,to,type){const bad=[]; if(!from||!to)bad.push('Choose two people.'); if(from===to)bad.push('A person cannot be related to themselves.'); if(S.relationships.some(r=>r.from_person_id===from&&r.to_person_id===to&&r.relationship_type===type))bad.push('This relationship already exists.'); if(type==='parent'&&ancestor(to,from))bad.push('This would create an ancestor loop.'); return bad}
export async function createRelationship(from,to,type,label){
  const bad=validateRelationship(from,to,type); if(bad.length)return{error:bad.join(' ')};
  const ins=await S.sb.from('relationships').insert({from_person_id:from,to_person_id:to,relationship_type:type,label:label||type,source_photo_id:S.currentPhoto?.id||null,created_by:S.session?.user?.id}).select().single();
  if(ins.error)return{error:ins.error.message};
  S.relationships.push(ins.data); return{data:ins.data};
}
function preview(){const w=$('relationshipWarning'); if(!w)return; const c=candidate(); const bad=validateRelationship(c.from,c.to,c.type); w.classList.toggle('hidden',!bad.length); w.classList.toggle('bad',!!bad.length); w.innerHTML=bad.join('<br>')}
export async function saveRelationship(){const c=candidate(); const res=await createRelationship(c.from,c.to,c.type,c.label); if(res.error){const w=$('relationshipWarning'); if(w){w.classList.remove('hidden');w.classList.add('bad');w.innerHTML=res.error} return} await renderPage('photo')}
export async function deleteRelationship(id){if(!canDelete())return alert('Only owner can delete relationships.'); const del=await S.sb.from('relationships').delete().eq('id',id); if(del.error)return alert(del.error.message); S.relationships=S.relationships.filter(r=>r.id!==id); renderRelationshipList()}
export function bindRelationships(){document.getElementById('relButtons')?.addEventListener('click',e=>{const b=e.target.closest('[data-rel]'); if(!b)return; S.currentRel=b.dataset.rel; document.querySelectorAll('#relButtons button').forEach(x=>x.classList.toggle('active',x===b)); preview()}); $('relA')?.addEventListener('change',preview); $('relB')?.addEventListener('change',preview); $('saveRelBtn')?.addEventListener('click',saveRelationship); document.body.addEventListener('click',e=>{const b=e.target.closest('[data-delete-rel]'); if(b)deleteRelationship(b.dataset.deleteRel)})}
