import { S, $, esc, fullName, person, visible } from './state.js';
import { avatarHtml } from './render.js';
function parentsOf(id){return S.relationships.filter(r=>r.relationship_type==='parent'&&r.to_person_id===id&&visible(person(r.from_person_id))).map(r=>r.from_person_id)}
function depth(id,seen=new Set()){if(seen.has(id))return 0; seen.add(id); const ps=parentsOf(id); return ps.length?1+Math.max(...ps.map(p=>depth(p,seen))):0}
function partnerPairs(){const out=[],seen=new Set(); S.relationships.filter(r=>r.relationship_type==='partner').forEach(r=>{const a=person(r.from_person_id),b=person(r.to_person_id); if(!visible(a)||!visible(b))return; const key=[a.id,b.id].sort().join('|'); if(!seen.has(key)){seen.add(key);out.push([a.id,b.id])}}); return out}
function parentGroups(){const by={}; S.relationships.filter(r=>r.relationship_type==='parent'&&visible(person(r.from_person_id))&&visible(person(r.to_person_id))).forEach(r=>(by[r.to_person_id]||=[]).push(r.from_person_id)); const groups={}; Object.entries(by).forEach(([child,ps])=>{const key=ps.slice().sort().join('|'); (groups[key]||={parents:ps.slice().sort(),children:[]}).children.push(child)}); return Object.values(groups)}
function layout(focusId){const nodeW=178,rowGap=330,startY=120; let people=S.people.filter(visible); const partner=new Map(); partnerPairs().forEach(([a,b])=>{partner.set(a,b);partner.set(b,a)}); const d={}; people.forEach(p=>d[p.id]=depth(p.id)); partnerPairs().forEach(([a,b])=>{const m=Math.max(d[a]||0,d[b]||0);d[a]=m;d[b]=m});
  const pos={};
  if(focusId&&d[focusId]!==undefined){const offset=d[focusId]; Object.keys(d).forEach(id=>d[id]=d[id]-offset);
    if(S.treeGenerationLimit!=='all') people=people.filter(p=>Math.abs(d[p.id])<=S.treeGenerationLimit);
  }
  const survivingDepths=people.map(p=>d[p.id]), minD=survivingDepths.length?Math.min(0,...survivingDepths):0; people.forEach(p=>d[p.id]=d[p.id]-minD);
  const rows={}, used=new Set(); people.forEach(p=>{if(used.has(p.id))return; let members=[p.id],q=partner.get(p.id); if(q&&!used.has(q)&&d[q]===d[p.id]&&people.some(x=>x.id===q)){members=[p.id,q].sort((a,b)=>fullName(person(a)).localeCompare(fullName(person(b))));used.add(q)} used.add(p.id); (rows[d[p.id]||0]||=[]).push({members,width:members.length*nodeW+(members.length-1)*46,x:0})}); Object.entries(rows).forEach(([k,units])=>{let x=220; units.sort((a,b)=>fullName(person(a.members[0])).localeCompare(fullName(person(b.members[0])))); units.forEach(u=>{u.x=x;x+=u.width+90;u.members.forEach((id,i)=>pos[id]={x:u.x+i*(nodeW+46),y:startY+(+k)*rowGap,unit:u})})}); return pos}
export async function renderTree(){const graph=$('graph'); if(!graph)return; graph.innerHTML='<div class="graph-inner" id="graphInner"></div>'; const inner=$('graphInner'), pos=layout(S.treeFocusId), nodeW=178,nodeH=156; function h(x,y,w){const e=document.createElement('div');e.className='line h';e.style.left=(w<0?x+w:x)+'px';e.style.top=y+'px';e.style.width=Math.abs(w)+'px';inner.appendChild(e)} function v(x,y,hh){const e=document.createElement('div');e.className='line v';e.style.left=x+'px';e.style.top=y+'px';e.style.height=Math.max(0,hh)+'px';inner.appendChild(e)} function lab(x,y,t){const e=document.createElement('div');e.className='rel-label';e.style.left=x+'px';e.style.top=y+'px';e.textContent=t;inner.appendChild(e)} partnerPairs().forEach(([a,b])=>{if(!pos[a]||!pos[b])return; const l=pos[a].x<pos[b].x?a:b, r=l===a?b:a, y=pos[l].y+74; h(pos[l].x+nodeW,y,pos[r].x-(pos[l].x+nodeW)); lab((pos[l].x+nodeW+pos[r].x)/2-35,y-27,'Partner')}); parentGroups().forEach(g=>{const ps=g.parents.filter(id=>pos[id]), cs=g.children.filter(id=>pos[id]); if(!ps.length||!cs.length)return; const pc=ps.reduce((s,id)=>s+pos[id].x+nodeW/2,0)/ps.length, bottom=Math.max(...ps.map(id=>pos[id].y+nodeH)), top=Math.min(...cs.map(id=>pos[id].y)), by=(bottom+top)/2; v(pc,bottom,by-bottom); const left=Math.min(...cs.map(id=>pos[id].x+nodeW/2)), right=Math.max(...cs.map(id=>pos[id].x+nodeW/2)); h(left,by,right-left); cs.forEach(id=>v(pos[id].x+nodeW/2,by,pos[id].y-by))}); for(const p of S.people.filter(visible)){if(!pos[p.id])continue; const xy=pos[p.id]; const n=document.createElement('div'); n.className='node'+(p.id===S.treeFocusId?' node-focused':''); n.dataset.treeFocus=p.id; n.style.left=xy.x+'px'; n.style.top=xy.y+'px'; n.innerHTML=`${await avatarHtml(p)}<strong>${esc(fullName(p))}</strong><span class="small">${esc(p.birth_date||'')}${p.death_date?' – '+esc(p.death_date):''}</span><a class="tree-view-profile" data-person-id="${p.id}">View profile →</a>`; inner.appendChild(n)} syncFocusChip(); if(S.treeFocusId&&pos[S.treeFocusId]) centerOn(pos[S.treeFocusId],nodeW,nodeH); applyZoom()}
function centerOn(xy,nodeW,nodeH){const wrap=$('graphWrap'); if(!wrap)return; wrap.scrollLeft=Math.max(0,xy.x+nodeW/2-wrap.clientWidth/2); wrap.scrollTop=Math.max(0,xy.y+nodeH/2-wrap.clientHeight/2)}
function syncFocusChip(){const chip=$('treeFocusChip'); const sel=$('treeGenerationSelect'); if(sel&&sel.value!==String(S.treeGenerationLimit))sel.value=String(S.treeGenerationLimit); if(!chip)return; if(!S.treeFocusId){chip.classList.add('hidden'); return} const p=person(S.treeFocusId); chip.classList.remove('hidden'); chip.querySelector('span').textContent='Focused on '+(p?fullName(p):'…')}
export function setTreeFocus(id){S.treeFocusId=id; renderTree()}
export function clearTreeFocus(){S.treeFocusId=null; renderTree()}
export function applyZoom(){const inner=$('graphInner'); if(inner)inner.style.transform=`scale(${S.graphScale})`; const z=$('zoomLabel'); if(z)z.textContent=Math.round(S.graphScale*100)+'%'}
export function fitGraph(){S.graphScale=.72; applyZoom(); const wrap=$('graphWrap'); if(wrap){wrap.scrollLeft=90;wrap.scrollTop=60}}
export function zoom(d){S.graphScale=Math.max(.25,Math.min(2.2,S.graphScale+d)); applyZoom()}
export function bindTree(){document.getElementById('rebuildGraphBtn')?.addEventListener('click',renderTree); document.getElementById('fitGraphBtn')?.addEventListener('click',fitGraph); document.getElementById('zoomInBtn')?.addEventListener('click',()=>zoom(.12)); document.getElementById('zoomOutBtn')?.addEventListener('click',()=>zoom(-.12)); document.getElementById('zoomResetBtn')?.addEventListener('click',()=>{S.graphScale=1;applyZoom()}); document.getElementById('themeRail')?.addEventListener('click',e=>{const b=e.target.closest('[data-theme]'); if(b){import('./state.js').then(m=>m.applyTheme(b.dataset.theme))}});
  document.getElementById('graph')?.addEventListener('click',e=>{if(e.target.closest('[data-person-id]'))return; const n=e.target.closest('[data-tree-focus]'); if(n)setTreeFocus(n.dataset.treeFocus)});
  document.getElementById('treeFocusChip')?.addEventListener('click',clearTreeFocus);
  document.getElementById('treeGenerationSelect')?.addEventListener('change',e=>{S.treeGenerationLimit=e.target.value==='all'?'all':+e.target.value; renderTree()});
}
