const faces=[{id:1,x:16,y:29,w:5,h:9},{id:2,x:20,y:27,w:5,h:8},{id:3,x:24,y:31,w:5,h:8},{id:4,x:28,y:29,w:5,h:8},{id:5,x:33,y:30,w:5,h:9},{id:6,x:38,y:31,w:5,h:8},{id:7,x:43,y:31,w:5,h:8},{id:8,x:48,y:30,w:5,h:9},{id:9,x:54,y:31,w:5,h:9},{id:10,x:59,y:31,w:5,h:8},{id:11,x:64,y:33,w:5,h:8},{id:12,x:69,y:32,w:5,h:8},{id:13,x:74,y:32,w:5,h:8},{id:14,x:79,y:31,w:5,h:8},{id:15,x:27,y:43,w:5,h:8},{id:16,x:34,y:43,w:5,h:8},{id:17,x:40,y:43,w:5,h:8},{id:18,x:47,y:44,w:5,h:8},{id:19,x:54,y:43,w:5,h:8},{id:20,x:61,y:43,w:5,h:8},{id:21,x:67,y:43,w:5,h:8},{id:22,x:74,y:43,w:5,h:8},{id:23,x:13,y:57,w:5,h:8},{id:24,x:21,y:62,w:5,h:8},{id:25,x:29,y:58,w:5,h:8},{id:26,x:36,y:59,w:5,h:8},{id:27,x:44,y:58,w:5,h:8},{id:28,x:51,y:58,w:5,h:8},{id:29,x:58,y:58,w:5,h:8},{id:30,x:66,y:58,w:5,h:8},{id:31,x:75,y:58,w:5,h:8},{id:32,x:10,y:71,w:5,h:8},{id:33,x:18,y:70,w:5,h:8},{id:34,x:39,y:72,w:5,h:8},{id:35,x:49,y:71,w:5,h:8}];
let selectedFace=null, relationships=[];
const demoNames={8:"Jean Canterbury",9:"Paul Canterbury",16:"Julian Canterbury",19:"Zoe Phillips",20:"Rachel Canterbury",22:"Andrew Canterbury"};
function init(){const wrap=document.getElementById("photoWrap");faces.forEach(f=>{const el=document.createElement("div");el.className="face";el.id="face-"+f.id;el.style.left=f.x+"%";el.style.top=f.y+"%";el.style.width=f.w+"%";el.style.height=f.h+"%";el.innerHTML="<span>Face "+f.id+"</span>";el.onclick=()=>selectFace(f.id);wrap.appendChild(el)});update()}
function selectFace(id){selectedFace=id;document.querySelectorAll(".face").forEach(e=>e.classList.remove("selected"));document.getElementById("face-"+id).classList.add("selected");const f=faces.find(x=>x.id===id);document.getElementById("editor").innerHTML=`<h2>Selected face ${id}</h2><div class="row"><label>Name</label><input id="nameInput" value="${f.name||""}" placeholder="Type full name"></div><div class="toolbar"><button class="primary" onclick="saveName()">Save name</button><button onclick="markUnknown()">Unknown</button></div><p>Once named, this face becomes a person record or links to an existing person.</p>`}
function saveName(){const name=document.getElementById("nameInput").value.trim();const f=faces.find(x=>x.id===selectedFace);f.name=name;const el=document.getElementById("face-"+selectedFace);el.classList.toggle("named",!!name);el.querySelector("span").textContent=name||("Face "+selectedFace);update()}
function markUnknown(){const f=faces.find(x=>x.id===selectedFace);f.name="Unknown "+selectedFace;document.getElementById("face-"+selectedFace).classList.add("named");document.getElementById("face-"+selectedFace).querySelector("span").textContent=f.name;update()}
function autoNameDemo(){faces.forEach(f=>{if(demoNames[f.id])f.name=demoNames[f.id];const el=document.getElementById("face-"+f.id);if(f.name){el.classList.add("named");el.querySelector("span").textContent=f.name}});relationships=[{a:"Jean Canterbury",type:"mother",b:"Julian Canterbury"},{a:"Paul Canterbury",type:"father",b:"Julian Canterbury"},{a:"Jean Canterbury",type:"mother",b:"Rachel Canterbury"},{a:"Paul Canterbury",type:"father",b:"Rachel Canterbury"},{a:"Jean Canterbury",type:"mother",b:"Andrew Canterbury"},{a:"Paul Canterbury",type:"father",b:"Andrew Canterbury"},{a:"Julian Canterbury",type:"partner",b:"Zoe Phillips"}];update()}
function namedPeople(){return[...new Set(faces.filter(f=>f.name).map(f=>f.name))].sort()}
function update(){document.getElementById("faceCount").textContent=faces.length;document.getElementById("namedCount").textContent=faces.filter(f=>f.name).length;document.getElementById("relCount").textContent=relationships.length;const people=namedPeople();document.getElementById("peopleList").innerHTML=people.map(p=>`<span class="person-pill">${p}</span>`).join("")||"<p>No names yet.</p>";["relA","relB"].forEach(id=>{const sel=document.getElementById(id);const old=sel.value;sel.innerHTML=people.map(p=>`<option>${p}</option>`).join("");if(people.includes(old))sel.value=old});drawMiniTree()}
function addRelationship(){const a=document.getElementById("relA").value,b=document.getElementById("relB").value,type=document.getElementById("relType").value;if(!a||!b||a===b)return alert("Choose two different people.");relationships.push({a,type,b});update()}
function drawMiniTree(){const t=document.getElementById("miniTree");t.innerHTML="";function node(name,x,y){const e=document.createElement("div");e.className="node";e.style.left=x+"px";e.style.top=y+"px";e.innerHTML="<strong>"+name.split(" ")[0]+"</strong>"+name.split(" ").slice(1).join(" ");t.appendChild(e)}function line(c,x,y,l){const e=document.createElement("div");e.className="line "+c;e.style.left=x+"px";e.style.top=y+"px";if(c==="h")e.style.width=l+"px";else e.style.height=l+"px";t.appendChild(e)}const has=name=>namedPeople().includes(name);if(has("Jean Canterbury"))node("Jean Canterbury",70,20);if(has("Paul Canterbury"))node("Paul Canterbury",230,20);if(has("Jean Canterbury")&&has("Paul Canterbury")){line("h",200,48,30);line("v",215,48,55);line("h",80,103,330)}if(has("Julian Canterbury"))node("Julian Canterbury",20,130);if(has("Rachel Canterbury"))node("Rachel Canterbury",165,130);if(has("Andrew Canterbury"))node("Andrew Canterbury",310,130);if(has("Zoe Phillips"))node("Zoe Phillips",20,205);if(has("Julian Canterbury")&&has("Zoe Phillips"))line("v",85,184,22)}
function exportData(){const data={people:namedPeople(),relationships};const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="photo-tree-relationships.json";a.click()}
init();